### ISSUE TITLE
Make clearer that clicking on issue leads to code highlight 

### ISSUE THREAD

**Issue by Gtonizuka** [aquiladev/remix-mythx-plugin#18]
It's not really clear that clicking on the issue title leads to code highlighting. How about putting that link only on the "line:column" part (but with link style)?
E.g.
`[1:0] A floating pragma is set [SWC-1xx]`< Link to SWC
^ Link to code

**Comment by aquiladev** [comment]
@Gtonizuka I'm not sure what do you mean 'Link style', because it is already link style.

I was playing with this UX, I would like to get feedback. I think to make it similar to a compiler style. A warning is a yellow button, error - red button

![image](https://user-images.githubusercontent.com/1164492/60382380-a22f6b80-9a62-11e9-89b1-f8400fe77e73.png)

**Comment by aquiladev** [comment]
@b-mueller @Gtonizuka @yann300 any thoughts about this UX?

**Comment by aquiladev** [comment]
decided to merge it, in case of any suggestions lets discuss it in different issue
