### ISSUE TITLE
Error message when wrong usr/pwd

### ISSUE THREAD

**Issue by Gtonizuka** [aquiladev/remix-mythx-plugin#41]
@aquiladev I still don't see this working...I thought it was deployed already?

**Comment by aquiladev** [comment]
@Gtonizuka you may have not seen error message straight after changing credentials, because login happens when you press `Analyze` button. When you click on the button with not valid credentials you should see:
![image](https://user-images.githubusercontent.com/1164492/68841557-7c32fc80-06cd-11ea-8a9c-3107061a5766.png)

**Comment by Gtonizuka** [comment]
ok thanks
